zmk_keycode_map:
  JP_DQUOTE: '"'
  JP_AMPERSAND: '&'
  JP_QUOTE: "'"
  JP_EQUAL: '='
  JP_CARET: '^'
  JP_YEN: '¥'
  JP_PLUS: '+'
  JP_TILDE: '~'
  JP_PIPE: '|'
  JP_AT: '@'
  JP_COLON: ':'
  JP_ASTERISK: '*'
  JP_BACKQUOTE: '`'
  JP_UNDERSCORE: '_'
  JP_LBRACKET: '['
  JP_RBRACKET: ']'
  JP_LPAREN: '('
  JP_RPAREN: ')'
  JP_LBRACE: '{'
  JP_RBRACE: '}'
  JP_KANA: 'かな'
  JP_EISU: '英数'
  JP_HANZEN: '半/全'